---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: issho/concourse-buildkit

params:
  CONTEXT: git
  REPOSITORY: issho/concourse-buildkit

inputs:
  - name: git

outputs:
  - name: image

caches:
  - path: cache

run:
  path: git/build
