---
resource_types:
  - name: concourse-pipeline
    type: registry-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/concourse-buildkit
      ignore_paths:
        - ci/
  - name: buildkit
    type: registry-image
    icon: docker
    source:
      repository: moby/buildkit
      tag: v0.6.0
  - name: concourse-buildkit
    type: registry-image
    icon: docker
    source:
      repository: issho/concourse-buildkit
      username: ((docker-hub.username))
      password: ((docker-hub.password))
  - name: pipeline-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/concourse-buildkit
      paths:
        - ci/
  - name: pipeline
    type: concourse-pipeline
    icon: fan
    source:
      teams:
        - name: main
          username: ((concourse.username))
          password: ((concourse.password))

groups:
  - name: build
    jobs:
      - build-image
  - name: pipeline
    jobs:
      - pipeline

jobs:
  - name: pipeline
    plan:
      - get: pipeline-git
        trigger: true
      - put: pipeline
        params:
          pipelines:
            - name: concourse-buildkit
              team: main
              config_file: pipeline-git/ci/pipeline.yml
  - name: build-image
    plan:
      - in_parallel:
          - get: git
            trigger: true
          - get: buildkit
            trigger: true
      - task: build
        file: git/ci/tasks/build.yml
        privileged: true
        output_mapping:
          image: concourse-buildkit
      - put: concourse-buildkit
        params:
          image: concourse-buildkit/image.tar
          additional_tags: git/.git/short_ref
